### PR TITLE
URA-56 som.py for uranus

### PR DESCRIPTION
**Pull request by Aisha-D**
- First version of som.py

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_sompy/1)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_sompy/1)* status: 1 of 6 files reviewed, 3 unresolved discussions (waiting on @Aisha-D and @jethror1)

___
*[`src/eggd_sompy.sh` line 20 at r1](https://reviewable.io/reviews/eastgenomics/eggd_sompy/1#-N5ZGukK7pcFZzlSkAB9:-N5ZGukK7pcFZzlSkABA:b-fi27f4) ([raw file](https://github.com/eastgenomics/eggd_sompy/blob/c16f6bf7f528661b1e1aeb79bd3538e8877a2c7c/src/eggd_sompy.sh#L20)):*
> ```Shell
>     # will install the missing libraries from the downloaded deb files
>     # (so as to not use internet)
>     sudo dpkg -i libtinfo5_6.2-0ubuntu2_amd64.deb
> ```

can we raise an issue about this please
___
*[`src/eggd_sompy.sh` line 27 at r1](https://reviewable.io/reviews/eastgenomics/eggd_sompy/1#-N5ZHjdD4NxOSVyRwvKR:-N5ZHjdECVeBGMwpCm9M:b-8mrwuh) ([raw file](https://github.com/eastgenomics/eggd_sompy/blob/c16f6bf7f528661b1e1aeb79bd3538e8877a2c7c/src/eggd_sompy.sh#L27)):*
> ```Shell
>     reference_file_path=$(echo ${reference_file_path%.*})
>     samtools faidx $reference_file_path
>     mv in/reference_file/*.fai .
> ```

is this not included with the line below?
___
*[`src/eggd_sompy.sh` line 41 at r1](https://reviewable.io/reviews/eastgenomics/eggd_sompy/1#-N5ZHufMCfVL2DwXfPwG:-N5ZHufMCfVL2DwXfPwH:byr4jc5) ([raw file](https://github.com/eastgenomics/eggd_sompy/blob/c16f6bf7f528661b1e1aeb79bd3538e8877a2c7c/src/eggd_sompy.sh#L41)):*
> ```Shell
>     # set up docker to run sompy
>     service docker start
>     gunzip $pkrusche_happy_docker
> ```

you should be able to directly docker load the compressed image?

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_sompy/1)* status: 1 of 6 files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[`src/eggd_sompy.sh` line 20 at r1](https://reviewable.io/reviews/eastgenomics/eggd_sompy/1#-N5ZGukK7pcFZzlSkAB9:-N5diUOS28YS2zT40XVC:b1dr46n) ([raw file](https://github.com/eastgenomics/eggd_sompy/blob/c16f6bf7f528661b1e1aeb79bd3538e8877a2c7c/src/eggd_sompy.sh#L20)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

can we raise an issue about this please
</blockquote></details>

no repo place to raise this but messaged Wook about this
___
*[`src/eggd_sompy.sh` line 27 at r1](https://reviewable.io/reviews/eastgenomics/eggd_sompy/1#-N5ZHjdD4NxOSVyRwvKR:-N5dg-PZ8RVTdV6l8LE6:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_sompy/blob/c16f6bf7f528661b1e1aeb79bd3538e8877a2c7c/src/eggd_sompy.sh#L27)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

is this not included with the line below?
</blockquote></details>

Done.
___
*[`src/eggd_sompy.sh` line 41 at r1](https://reviewable.io/reviews/eastgenomics/eggd_sompy/1#-N5ZHufMCfVL2DwXfPwG:-N5dg-DW6pQlJxjFcg12:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_sompy/blob/c16f6bf7f528661b1e1aeb79bd3538e8877a2c7c/src/eggd_sompy.sh#L41)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

you should be able to directly docker load the compressed image?
</blockquote></details>

Done.

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_sompy/1)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @Aisha-D and @jethror1)

___
*[`resources/home/dnanexus/libncurses5_6.2-0ubuntu2_amd64.deb` line 0 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sompy/1#-N5j8tHY2MZ6ixGZAT6V:-N5j8tHY2MZ6ixGZAT6W:b-mncath) ([raw file](https://github.com/eastgenomics/eggd_sompy/blob/803f1ce9e2620eba8e396b3e340f18f3a6649d2f/resources/home/dnanexus/libncurses5_6.2-0ubuntu2_amd64.deb#L0)):*
can these be deleted now?

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_sompy/1)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @Aisha-D and @jethror1)

___
*[`dxapp.json` line 6 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sompy/1#-N5j9byU5BTKPCNzTBNJ:-N5j9byU5BTKPCNzTBNK:b-4ux9g) ([raw file](https://github.com/eastgenomics/eggd_sompy/blob/803f1ce9e2620eba8e396b3e340f18f3a6649d2f/dxapp.json#L6)):*
> ```JSON
>   "summary": "Somatic Variant Benchmarking Tool",
>   "dxapi": "1.0.0",
>   "version": "0.0.1",
> ```

is it still in development? can this be `1.0.0`?
___
*[`dxapp.json` line 77 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sompy/1#-N5j90rs-SFGXSAQN3Wr:-N5j90rs-SFGXSAQN3Ws:bvqt7dn) ([raw file](https://github.com/eastgenomics/eggd_sompy/blob/803f1ce9e2620eba8e396b3e340f18f3a6649d2f/dxapp.json#L77)):*
> ```JSON
>     "timeoutPolicy": {
>       "*": {
>         "hours": 48
> ```

can this be more strict? I assume its pretty quick and we don't want it running for that long if it hangs
___
*[`dxapp.json` line 85 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sompy/1#-N5j99pp4jWrgTcMXKvJ:-N5j99pp4jWrgTcMXKvK:b-zm0jv) ([raw file](https://github.com/eastgenomics/eggd_sompy/blob/803f1ce9e2620eba8e396b3e340f18f3a6649d2f/dxapp.json#L85)):*
> ```JSON
>     "release": "20.04",
>     "version": "0",
>     "assetDepends": [
> ```

this no longer needed?

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_sompy/1)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @jethror1)

___
*[`dxapp.json` line 6 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sompy/1#-N5j9byU5BTKPCNzTBNJ:-N5jEALG-gpR6VasD9pn:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_sompy/blob/803f1ce9e2620eba8e396b3e340f18f3a6649d2f/dxapp.json#L6)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

is it still in development? can this be `1.0.0`?
</blockquote></details>

Done.
___
*[`dxapp.json` line 77 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sompy/1#-N5j90rs-SFGXSAQN3Wr:-N5jE9TI7KpwX9A9VgZV:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_sompy/blob/803f1ce9e2620eba8e396b3e340f18f3a6649d2f/dxapp.json#L77)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

can this be more strict? I assume its pretty quick and we don't want it running for that long if it hangs
</blockquote></details>

Done.
___
*[`dxapp.json` line 85 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sompy/1#-N5j99pp4jWrgTcMXKvJ:-N5jE8BgC2TnkvUgaXWb:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_sompy/blob/803f1ce9e2620eba8e396b3e340f18f3a6649d2f/dxapp.json#L85)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

this no longer needed?
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/libncurses5_6.2-0ubuntu2_amd64.deb` line  at r2](https://reviewable.io/reviews/eastgenomics/eggd_sompy/1#-N5j8tHY2MZ6ixGZAT6V:-N5jE8vbEIYqvSShIxzI:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_sompy/blob/803f1ce9e2620eba8e396b3e340f18f3a6649d2f/resources/home/dnanexus/libncurses5_6.2-0ubuntu2_amd64.deb#L)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

can these be deleted now?
</blockquote></details>

Done.

**Pull request merged**
